var D = {
  code: 200,
  data: [
    {
      group: {
        id: 5,
        name: "tel-jssz-ks",
        chname: "昆山电信-20G",
        pop_id: 6,
        pop_name: "江苏苏州电信",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "offline",
        mode: "manual",
        comment: "",
        bandwidth: 23,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-23T16:46:29+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:26+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "江苏电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 9,
          ip: "180.97.72.181",
          group_id: 5,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498191244,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 10,
          ip: "180.97.72.182",
          group_id: 5,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498191244,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 6,
        name: "mob-zjhz-hz",
        chname: "浙江移动石桥-10G",
        pop_id: 7,
        pop_name: "浙江杭州移动",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "offline",
        mode: "manual",
        comment: "",
        bandwidth: 1659,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:26+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "浙江移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 11,
          ip: "117.148.129.15",
          group_id: 6,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498456798,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 12,
          ip: "117.148.129.16",
          group_id: 6,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498456798,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 40,
        name: "msrc-tel-nb-gate-io",
        chname: "浙江宁波电信",
        pop_id: 41,
        pop_name: "浙江宁波中间源",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "offline",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-22T10:19:16+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "浙江电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 79,
          ip: "115.231.182.56",
          group_id: 40,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 80,
          ip: "115.231.182.57",
          group_id: 40,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 81,
          ip: "115.231.182.58",
          group_id: 40,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 82,
          ip: "115.231.182.59",
          group_id: 40,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 83,
          ip: "115.231.182.60",
          group_id: 40,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 41,
        name: "msrc-cnc-nb-gate-io",
        chname: "浙江宁波联通",
        pop_id: 41,
        pop_name: "浙江宁波中间源",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "offline",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-22T10:22:50+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "浙江联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 84,
          ip: "101.71.81.106",
          group_id: 41,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 85,
          ip: "101.71.81.107",
          group_id: 41,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 86,
          ip: "101.71.81.108",
          group_id: 41,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 87,
          ip: "101.71.81.109",
          group_id: 41,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 88,
          ip: "101.71.81.110",
          group_id: 41,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 42,
        name: "msrc-mob-nb-gate-io",
        chname: "浙江宁波移动",
        pop_id: 41,
        pop_name: "浙江宁波中间源",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "offline",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-22T10:23:35+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "浙江移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 89,
          ip: "120.199.81.106",
          group_id: 42,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 90,
          ip: "120.199.81.107",
          group_id: 42,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 91,
          ip: "120.199.81.108",
          group_id: 42,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 92,
          ip: "120.199.81.109",
          group_id: 42,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 93,
          ip: "120.199.81.110",
          group_id: 42,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 34,
        name: "pbs-bj-bj",
        chname: "合作期:（鹏博士节点）",
        pop_id: 40,
        pop_name: "北京鹏博士",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:37+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "鹏博士",
        crash_status: "offline"
      },
      vip_list: [
        {
          id: 67,
          ip: "211.167.229.10",
          group_id: 34,
          use: true,
          final_status: "online",
          monitor_status: "offline",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 68,
          ip: "211.167.229.11",
          group_id: 34,
          use: true,
          final_status: "online",
          monitor_status: "offline",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 38,
        name: "mob-hbxy-xy",
        chname: "湖北襄阳-10G",
        pop_id: 37,
        pop_name: "湖北襄阳移动",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 5125,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-29T11:58:28+08:00",
        band_op_status: "normal",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:45+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "湖北移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 75,
          ip: "111.47.231.110",
          group_id: 38,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 76,
          ip: "111.47.231.109",
          group_id: 38,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 43,
        name: "msrc-tel-xs-gate-io",
        chname: "杭州下沙电信",
        pop_id: 42,
        pop_name: "杭州下沙中间源",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-22T11:21:46+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "浙江电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 94,
          ip: "115.238.101.14",
          group_id: 43,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 95,
          ip: "115.238.101.15",
          group_id: 43,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 96,
          ip: "115.238.101.16",
          group_id: 43,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 97,
          ip: "115.238.101.17",
          group_id: 43,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 98,
          ip: "115.238.101.18",
          group_id: 43,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 44,
        name: "msrc-cnc-xs-gate-io",
        chname: "杭州下沙联通",
        pop_id: 42,
        pop_name: "杭州下沙中间源",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-22T11:22:31+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "浙江联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 99,
          ip: "124.160.124.14",
          group_id: 44,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 100,
          ip: "124.160.124.15",
          group_id: 44,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 101,
          ip: "124.160.124.16",
          group_id: 44,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 102,
          ip: "124.160.124.17",
          group_id: 44,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 103,
          ip: "124.160.124.18",
          group_id: 44,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 45,
        name: "msrc-mob-xs-gate-io",
        chname: "杭州下沙移动",
        pop_id: 42,
        pop_name: "杭州下沙中间源",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-22T11:23:30+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "浙江移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 105,
          ip: "112.13.166.45",
          group_id: 45,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 106,
          ip: "112.13.166.46",
          group_id: 45,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 107,
          ip: "112.13.166.47",
          group_id: 45,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 108,
          ip: "112.13.166.48",
          group_id: 45,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: false,
          comment: ""
        },
        {
          id: 109,
          ip: "112.13.166.44",
          group_id: 45,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 46,
        name: "msrc-tel-tj-gate-io",
        chname: "华北天津电信机房",
        pop_id: 44,
        pop_name: "华北天津机房",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-30T17:26:28+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "天津电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 110,
          ip: "42.81.112.32",
          group_id: 46,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 111,
          ip: "42.81.112.33",
          group_id: 46,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 112,
          ip: "42.81.112.34",
          group_id: 46,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 113,
          ip: "42.81.112.35",
          group_id: 46,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 114,
          ip: "42.81.112.36",
          group_id: 46,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 47,
        name: "msrc-cnc-tj-gate-io",
        chname: "华北天津联通机房",
        pop_id: 44,
        pop_name: "华北天津机房",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-30T17:27:30+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "天津联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 115,
          ip: "220.194.102.32",
          group_id: 47,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 116,
          ip: "220.194.102.33",
          group_id: 47,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 117,
          ip: "220.194.102.34",
          group_id: 47,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 118,
          ip: "220.194.102.35",
          group_id: 47,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 119,
          ip: "220.194.102.36",
          group_id: 47,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 48,
        name: "msrc-mob-tj-gate-io",
        chname: "华北天津移动",
        pop_id: 44,
        pop_name: "华北天津机房",
        pop_chname: "",
        pop_total_bandwidth: 100000,
        pop_bandwidth: 0,
        platform_id: 1,
        role: "midsrc",
        service_status: "online",
        final_status: "online",
        mode: "manual",
        comment: "",
        bandwidth: 0,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-30T17:28:21+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "天津移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 120,
          ip: "117.131.210.8",
          group_id: 48,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 121,
          ip: "117.131.210.9",
          group_id: 48,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 122,
          ip: "117.131.210.10",
          group_id: 48,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 123,
          ip: "117.131.210.11",
          group_id: 48,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 124,
          ip: "117.131.210.12",
          group_id: 48,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 1,
        name: "cnc-gddg-dg",
        chname: "东莞联通-10G",
        pop_id: 2,
        pop_name: "广东东莞联通",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 4892,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:25+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "广东联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 1,
          ip: "157.255.158.79",
          group_id: 1,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 2,
          ip: "157.255.158.80",
          group_id: 1,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 2,
        name: "tel-gzfs-pz",
        chname: "佛山平洲-20G",
        pop_id: 3,
        pop_name: "广东佛山电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 6283,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-30T07:31:51+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:25+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "广东电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 3,
          ip: "183.2.208.21",
          group_id: 2,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 4,
          ip: "183.2.208.22",
          group_id: 2,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 3,
        name: "mob-gdgz-gz",
        chname: "广州南方基地-10G",
        pop_id: 5,
        pop_name: "广东广州移动",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 10448,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:25+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "广东移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 5,
          ip: "183.240.24.15",
          group_id: 3,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 6,
          ip: "183.240.24.16",
          group_id: 3,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 4,
        name: "cnc-tj-tj",
        chname: "天津空港-20G",
        pop_id: 4,
        pop_name: "天津空港联通",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 6239,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-25T04:24:22+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:26+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "天津联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 7,
          ip: "125.39.7.181",
          group_id: 4,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 8,
          ip: "125.39.7.182",
          group_id: 4,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 7,
        name: "tel-hbhg-hg",
        chname: "湖北黄冈 -10G",
        pop_id: 16,
        pop_name: "湖北黄冈电信",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 9658,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:26+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "湖北电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 13,
          ip: "58.51.100.16",
          group_id: 7,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 14,
          ip: "58.51.100.17",
          group_id: 7,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 8,
        name: "cnc-hnxx-xx",
        chname: "河南新乡-10G",
        pop_id: 12,
        pop_name: "河南新乡联通",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 7790,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:26+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "河南联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 15,
          ip: "61.163.120.144",
          group_id: 8,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 16,
          ip: "61.163.120.145",
          group_id: 8,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 9,
        name: "mob-hnxx-xx",
        chname: "新乡移动-10G",
        pop_id: 11,
        pop_name: "河南新乡移动",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 4766,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:27+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "河南移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 17,
          ip: "117.159.35.208",
          group_id: 9,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 18,
          ip: "117.159.35.209",
          group_id: 9,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 10,
        name: "tel-gddg-dg",
        chname: "东莞电信-10G",
        pop_id: 8,
        pop_name: "广东东莞电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 2300,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-22T07:57:34+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:27+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "广东电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 19,
          ip: "113.105.169.16",
          group_id: 10,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 20,
          ip: "113.105.169.17",
          group_id: 10,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 11,
        name: "cnc-lnsy-sy",
        chname: "沈阳联通-10G",
        pop_id: 15,
        pop_name: "辽宁沈阳联通",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 4940,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:27+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "辽宁联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 21,
          ip: "124.95.147.80",
          group_id: 11,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 22,
          ip: "124.95.147.81",
          group_id: 11,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 12,
        name: "mob-sccd-cd",
        chname: "成都移动-10G-31700",
        pop_id: 10,
        pop_name: "四川成都移动",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 4829,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:28+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "四川移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 23,
          ip: "117.177.245.144",
          group_id: 12,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 24,
          ip: "117.177.245.145",
          group_id: 12,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 13,
        name: "tel-zjsx-sx",
        chname: "浙江绍兴电信-10G-31900",
        pop_id: 14,
        pop_name: "浙江绍兴电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 6623,
        bandwidth_time: "2017-07-03T17:10:48+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:28+08:00",
        updated: "2017-07-03T17:10:48+08:00",
        view: "浙江电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 25,
          ip: "183.131.87.16",
          group_id: 13,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 26,
          ip: "183.131.87.17",
          group_id: 13,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 14,
        name: "cnc-sdta-ta",
        chname: "泰安联通-10G-32500",
        pop_id: 13,
        pop_name: "山东泰安联通",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 5522,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:28+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "山东联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 27,
          ip: "61.162.231.211",
          group_id: 14,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 28,
          ip: "61.162.231.212",
          group_id: 14,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 15,
        name: "tel-sccd-cd",
        chname: "成都电信-20G-33100",
        pop_id: 9,
        pop_name: "四川成都电信",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 12022,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:28+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "四川电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 29,
          ip: "182.150.14.21",
          group_id: 15,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 30,
          ip: "182.150.14.22",
          group_id: 15,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 16,
        name: "cnc-hbts-ts",
        chname: "唐山联通-10G（接信安设备）",
        pop_id: 26,
        pop_name: "河北唐山联通",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 5487,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:29+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "河北联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 31,
          ip: "60.2.148.206",
          group_id: 16,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 32,
          ip: "60.2.148.207",
          group_id: 16,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 17,
        name: "tel-zjqz-qz",
        chname: "浙江衢州电信-10G（接信安设备）",
        pop_id: 27,
        pop_name: "浙江衢州电信",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 8761,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:29+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "浙江电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 33,
          ip: "183.136.218.206",
          group_id: 17,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 34,
          ip: "183.136.218.207",
          group_id: 17,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 18,
        name: "tel-jszj-zj",
        chname: "江苏镇江电信-40G",
        pop_id: 24,
        pop_name: "江苏镇江电信",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 20836,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:29+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "江苏电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 35,
          ip: "222.186.140.14",
          group_id: 18,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 36,
          ip: "222.186.140.15",
          group_id: 18,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 19,
        name: "tel-gdhz-hz",
        chname: "广东惠州电信-10G（接信安设备）",
        pop_id: 20,
        pop_name: "广东惠州电信",
        pop_chname: "",
        pop_total_bandwidth: 30000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 7214,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:29+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "广东电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 37,
          ip: "121.15.220.14",
          group_id: 19,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 38,
          ip: "121.15.220.15",
          group_id: 19,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 20,
        name: "tel-gzgy-gy",
        chname: "贵州贵阳电信-10G",
        pop_id: 30,
        pop_name: "贵州贵阳电信",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 3888,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:30+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "贵州电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 39,
          ip: "42.123.110.109",
          group_id: 20,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 40,
          ip: "42.123.110.110",
          group_id: 20,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 21,
        name: "tel-fjfz-fz",
        chname: "福建福州电信-10G-31800",
        pop_id: 29,
        pop_name: "福建福州电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 6959,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-21T21:19:06+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:30+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "福建电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 41,
          ip: "27.155.95.237",
          group_id: 21,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498672908,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 42,
          ip: "27.155.95.238",
          group_id: 21,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498672908,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 22,
        name: "tel-lnsy-sy",
        chname: "辽宁沈阳电信-10G-32000",
        pop_id: 31,
        pop_name: "辽宁沈阳电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 2815,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:30+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "辽宁电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 43,
          ip: "59.44.28.141",
          group_id: 22,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 44,
          ip: "59.44.28.142",
          group_id: 22,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 23,
        name: "tel-hnhy-hy",
        chname: "湖南衡阳电信-10G-32100",
        pop_id: 28,
        pop_name: "湖南衡阳电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 7271,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-29T08:26:49+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:30+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "湖南电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 45,
          ip: "175.6.232.13",
          group_id: 23,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498665953,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 46,
          ip: "175.6.232.14",
          group_id: 23,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 1498665953,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 24,
        name: "tel-gxnn-nn",
        chname: "广西南宁电信-10G-32300",
        pop_id: 21,
        pop_name: "广西南宁电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 3929,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:31+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "广西电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 47,
          ip: "116.253.191.45",
          group_id: 24,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 48,
          ip: "116.253.191.46",
          group_id: 24,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 25,
        name: "cnc-jlcc-cc",
        chname: "吉林长春联通-10G-32400",
        pop_id: 17,
        pop_name: "吉林长春联通",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 3607,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:31+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "吉林联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 49,
          ip: "122.143.20.13",
          group_id: 25,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 50,
          ip: "122.143.20.14",
          group_id: 25,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 26,
        name: "cnc-cq-cq",
        chname: "重庆联通-10G-32200",
        pop_id: 32,
        pop_name: "重庆北培联通",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 2809,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:32+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "重庆联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 51,
          ip: "113.207.123.141",
          group_id: 26,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 52,
          ip: "113.207.123.142",
          group_id: 26,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 27,
        name: "tel-tj-tj",
        chname: "天津天津电信-32600",
        pop_id: 18,
        pop_name: "天津武清电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 2703,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:33+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "天津电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 53,
          ip: "42.81.55.141",
          group_id: 27,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 54,
          ip: "42.81.55.142",
          group_id: 27,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 28,
        name: "cnc-jswx-wx",
        chname: "江苏无锡联通-32700",
        pop_id: 22,
        pop_name: "江苏无锡联通",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 2316,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:35+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "江苏联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 55,
          ip: "122.193.203.205",
          group_id: 28,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 56,
          ip: "122.193.203.206",
          group_id: 28,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 29,
        name: "tel-sxxy-xy",
        chname: "陕西咸阳电信-32800",
        pop_id: 33,
        pop_name: "陕西咸阳电信",
        pop_chname: "",
        pop_total_bandwidth: 40000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 5664,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:36+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "陕西电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 57,
          ip: "36.42.77.14",
          group_id: 29,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 58,
          ip: "36.42.77.15",
          group_id: 29,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 30,
        name: "mob-jssz-sz",
        chname: "江苏苏州移动-32900",
        pop_id: 23,
        pop_name: "江苏苏州移动",
        pop_chname: "",
        pop_total_bandwidth: 60000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 12494,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-30T07:32:22+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:36+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "江苏移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 59,
          ip: "223.111.253.13",
          group_id: 30,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 60,
          ip: "223.111.253.14",
          group_id: 30,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 31,
        name: "cnc-sxxa-xa",
        chname: "陕西西安联通-33000",
        pop_id: 34,
        pop_name: "陕西西安联通",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 1488,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:36+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "陕西联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 61,
          ip: "113.200.108.206",
          group_id: 31,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 62,
          ip: "113.200.108.207",
          group_id: 31,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 32,
        name: "mob-tj-tj",
        chname: "天津天津移动 cdn-mob-tj-tj-[1-6]",
        pop_id: 19,
        pop_name: "天津空港移动",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 3337,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:37+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "天津移动",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 63,
          ip: "117.131.203.141",
          group_id: 32,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 64,
          ip: "117.131.203.142",
          group_id: 32,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 33,
        name: "tel-hbts-ts",
        chname: "河北唐山电信-33300",
        pop_id: 25,
        pop_name: "河北唐山电信",
        pop_chname: "",
        pop_total_bandwidth: 20000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 2139,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "2017-06-23T08:34:16+08:00",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:37+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "河北电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 65,
          ip: "222.222.204.14",
          group_id: 33,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 66,
          ip: "222.222.204.15",
          group_id: 33,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 35,
        name: "cnc-sdjn-jn",
        chname: "济南联通-10G",
        pop_id: 35,
        pop_name: "山东济南联通",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 4628,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:37+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "山东联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 69,
          ip: "119.188.128.13",
          group_id: 35,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 70,
          ip: "119.188.128.14",
          group_id: 35,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 36,
        name: "tel-gslz-lz",
        chname: "甘肃兰州电信-10G",
        pop_id: 38,
        pop_name: "甘肃兰州电信",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 1740,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:37+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "甘肃电信",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 71,
          ip: "118.180.55.13",
          group_id: 36,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 72,
          ip: "118.180.55.14",
          group_id: 36,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    },
    {
      group: {
        id: 37,
        name: "cnc-hbwh-wh",
        chname: "湖北武汉-10G",
        pop_id: 36,
        pop_name: "湖北武汉联通",
        pop_chname: "",
        pop_total_bandwidth: 10000,
        pop_bandwidth: 0,
        platform_id: 2,
        role: "cluster",
        service_status: "online",
        final_status: "online",
        mode: "auto",
        comment: "",
        bandwidth: 2134,
        bandwidth_time: "2017-07-03T17:10:49+08:00",
        avail_bandwidth: 0,
        band_op_time: "0001-01-01T00:00:00Z",
        band_op_status: "",
        band_status: "online",
        event_id: 0,
        created: "2017-06-21T09:55:38+08:00",
        updated: "2017-07-03T17:10:49+08:00",
        view: "湖北联通",
        crash_status: "online"
      },
      vip_list: [
        {
          id: 73,
          ip: "183.95.81.231",
          group_id: 37,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        },
        {
          id: 74,
          ip: "183.95.81.232",
          group_id: 37,
          use: true,
          final_status: "online",
          monitor_status: "online",
          monitor_update_time: 0,
          is_in_monitor: true,
          comment: ""
        }
      ],
      rip_list: null
    }
  ]
};

function funq(data) {
  if (!data) {
    return;
  }
  var newD = [];
  data.forEach((its, index, arr) => {
    if (its.vip_list) {
      its.vip_list.forEach((it, index, arr) => {
        newD.push({
          ipit: it,
          group: its.group
        });
      });
    }
  });
  return newD;
}

console.log(funq(D.data));
console.log(funq(D.data).length);
